# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Lighthouse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  react_native_path = '../node_modules/react-native'

  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'


  # Pods for Lighthouse
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'


  pod 'Yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'BatchedBridge',
    'ART',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTPushNotification',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  target 'LighthouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Lighthouse-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lighthouse-tvOS

  target 'Lighthouse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
